---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mission-control-strip-api
  namespace: mission-control
spec:
  stripPrefix:
    prefixes:
      - /api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mission-control
  namespace: mission-control
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: mission-control-mission-control-strip-api@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - mission-control.radicalgeek.co.uk
    secretName: mission-control-tls
  rules:
  - host: mission-control.radicalgeek.co.uk
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mission-control-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mission-control-frontend
            port:
              number: 3000
