---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mission-control
  namespace: mission-control
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - mission-control.radicalgeek.co.uk
    secretName: mission-control-tls
  rules:
  - host: mission-control.radicalgeek.co.uk
    http:
      paths:
      - path: /healthz
        pathType: Exact
        backend:
          service:
            name: mission-control-backend
            port:
              number: 8000
      - path: /readyz
        pathType: Exact
        backend:
          service:
            name: mission-control-backend
            port:
              number: 8000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: mission-control-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mission-control-frontend
            port:
              number: 3000
